gos:  
  messaging:
    prefix: ioq
    queues:
      labview: ${gos.messaging.prefix}.dht

logging:
  file: ioq-routes.log
  
spring:
  profile: general
  
  activemq:
    broker-url: tcp://192.168.10.168:61616
  
  datasource:
    initialize: true
    url: jdbc:postgresql://192.168.10.168:5432/iot
    driverClassName: org.postgresql.Driver
    username: orri
    password: Bios93

name: general-profile
environment: general

camel:
  springboot:
    # The Camel context name
    name: GosActiveMqToPostgrSql
    mainRunController: true
